on:
  push:
    branches:
      - main
name: release
env:
  FORCE_COLOR: 2
  NODE: 24
jobs:
  release-please:
    if: github.repository == 'JustinBeckwith/linkinator'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE }}
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p build/binaries
      - run: npm run build-binaries
      - name: Upload binaries to release
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} build/binaries/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
